name: leleya_hair_salon

services:
  postgres:
    image: postgres:16-alpine
    container_name: leleya_postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_DB: leleya_db
      POSTGRES_USER: leleya_admin
      POSTGRES_PASSWORD: super_secure_password_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U leleya_admin -d leleya_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: postgres_data
